defaults:
    - override hydra/launcher: submitit_local

# sileo
buffer_leeway : 2
manual_buffer: 0
rotate_step: 20
think_every: 100000
pretrain_frac: 0.4
buffer_max_length: 10000
pruning: true
first_prune: true
pruning_factor: 2
k_means_attempts: 20
max_primitives: 128
split_frac: 0.5


load_pretrained: false
compress_action_buffer: false
pretrained_model_path: ???
transfer_mode: 0
match_actions: true
matching_factor: 4
secondary_task: ???

# environment
task: dog-run
obs: state
num_envs: 4

# evaluation
checkpoint: ???
eval_episodes: 10
eval_freq: 50000

# training
steps: 10_000_000
batch_size: 256
steps_per_update: 4
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
lr: 3e-4
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 1_000_000
exp_name: default
data_dir: /envs

# planning
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 3
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10

# architecture
model_size: ???
num_enc_layers: 2
enc_dim: 256
num_channels: 32
mlp_dim: 512
latent_dim: 512
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8

# logging
wandb_project: ????
wandb_entity: ????
wandb_silent: false
disable_wandb: true
save_csv: true

# misc
save_video: true
save_agent: true
seed: 4

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???
